# Generated by Django 4.2.1 on 2023-06-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_event_eventcategory_event_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
