# Generated by Django 4.2.1 on 2023-06-12 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_booking_tickettype_bookingticketinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingticketinfo',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingticketinfo',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='event',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='eventcategory',
            name='event',
        ),
        migrations.RemoveField(
            model_name='tickettype',
            name='event',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingTicketInfo',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventCategory',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
