# Generated by Django 4.2.1 on 2023-06-21 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_quantity_delete_bookingticketinfo'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=8),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
    ]
