# Generated by Django 4.2.1 on 2023-06-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_event_price_event_mid_event_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mid_q',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='standard_q',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='vip_q',
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('finished', 'Finished')], default='pending', max_length=50),
        ),
    ]
