# Generated by Django 4.2.1 on 2023-06-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_mid_q_event_standard_q_event_vip_q_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='mid_q',
            new_name='mid_left',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='standard_q',
            new_name='standard_left',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='vip_q',
            new_name='vip_left',
        ),
    ]
