# Generated by Django 4.2.1 on 2023-06-26 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_event_mid_left_alter_event_standard_left_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='mid_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='standard_left',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='vip_left',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
